### ISSUE TITLE
Can't create note

### ISSUE THREAD

**Issue by mendelgordon** [DBelwnhs/React-Notes#1]
<img width="1503" alt="image" src="https://github.com/DBelwnhs/React-Notes/assets/30062581/97194649-f7a5-4533-82f6-a67c30745a25">
When I open the page I get some errors in the console, and pressing "Create one now' doesn't do anything

index-2a2c3bf9.js:2019 Uncaught TypeError: Cannot read properties of undefined (reading 'body')
    at index-2a2c3bf9.js:2019:717
index-2a2c3bf9.js:369 [2023-07-03T15:22:45.436Z]  @firebase/firestore: Firestore (9.20.0): Uncaught Error in snapshot listener: FirebaseError: [code=permission-denied]: Missing or insufficient permissions.
w8 @ index-2a2c3bf9.js:369
index-2a2c3bf9.js:2019 Uncaught (in promise) FirebaseError: Missing or insufficient permissions.

**Comment by DBelwnhs** [comment]
Hello, thank you for reaching out about this error. This was a mistake i made but its all fixed now!

**Comment by mendelgordon** [comment]
It still doesn't work for me

**Comment by DBelwnhs** [comment]
Alright. I'll look into that soon and i'll get back to you.
